// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzyohssalaivehujkngi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6eW9oc3NhbGFpdmVodWprbmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMTkzOTYsImV4cCI6MjA3NjY5NTM5Nn0.aKe7OB0DR7UpHAoYE9XcbrDCDkHbSY8yCwe-XNBsqXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});